using System;
using System.Collections;
using System.Collections.Generic;
using DSB.GC.Log;
using DSB.GC.RuntimeMessages;
using UnityEngine;

namespace DSB.GC
{
    public enum GCPlayerStatus
    {
        Neutral = 0,
        Pending = 1,
        Success = 2,
        Failure = 3,
        Warning = 4,
        Alert = 5
    }

    public enum GCPlayerEliminationState
    {
        None = 0,
        Revokable = 1,
        Permanent = 2
    }

    public enum GCPlayerFinishState
    {
        None = 0,
        Revokable = 1,
        Permanent = 2
    }

    public struct GCPlayerEliminationStateChangedEventArgs
    {
        public int playerIndex;
        public GCPlayerEliminationState oldState;
        public GCPlayerEliminationState newState;
        public string reason;
        public float changedAtGameTime;

        public GCPlayerEliminationStateChangedEventArgs(
            int playerIndex,
            GCPlayerEliminationState oldState,
            GCPlayerEliminationState newState,
            string reason,
            float changedAtGameTime
        )
        {
            this.playerIndex = playerIndex;
            this.oldState = oldState;
            this.newState = newState;
            this.reason = reason;
            this.changedAtGameTime = changedAtGameTime;
        }
    }

    public struct GCPlayerFinishStateChangedEventArgs
    {
        public int playerIndex;
        public GCPlayerFinishState oldState;
        public GCPlayerFinishState newState;
        public string reason;
        public float changedAtGameTime;

        public GCPlayerFinishStateChangedEventArgs(
            int playerIndex,
            GCPlayerFinishState oldState,
            GCPlayerFinishState newState,
            string reason,
            float changedAtGameTime
        )
        {
            this.playerIndex = playerIndex;
            this.oldState = oldState;
            this.newState = newState;
            this.reason = reason;
            this.changedAtGameTime = changedAtGameTime;
        }
    }

    public class GCPlayer : MonoBehaviour
    {
        public Action<GCPlayerEliminationStateChangedEventArgs> OnEliminationStateChanged;
        public Action<GCPlayerFinishStateChangedEventArgs> OnFinishStateChanged;
        public Action<int, int, string> OnScoreChanged;
        public Action<int, int, string> OnLivesChanged;
        public Action<int, int, string> OnMeterChanged;
        public Action<GCPlayerStatus, string, string> OnStatusChanged;
        internal Action<GCPlayerStatus, string, GCPlayerStatus, string, string> OnStatusTransitionChanged;
        internal event Action<GCPlayerAcceptedTransition> AcceptedTransition;
        public GCPlayerType PlayerType = GCPlayerType.unset;
        public bool IsBot => PlayerType == GCPlayerType.bot;
        private int index = -1;
        public int Index => index;
        private int playerSeed = -1;
        /// <summary>
        /// Deterministic player-specific seed generated by the platform from player-owned identity.
        /// </summary>
        public int PlayerSeed => playerSeed;
        private int id = -1;
        /// <summary>
        /// Removed. Use Index for game-facing player identity.
        /// </summary>
        [Obsolete("GCPlayer.Id has been removed from the game-facing runtime contract. Use GCPlayer.Index.", true)]
        public int Id => id;
        private string playerName = null;
        /// <summary>
        /// Removed. Player names are platform-owned and are not exposed to Unity game code.
        /// </summary>
        [Obsolete("GCPlayer.PlayerName has been removed from the game-facing runtime contract. Player names are platform-owned.", true)]
        public string PlayerName => playerName;
        /// <summary>
        /// GamingCouch player color "base" variant.
        /// </summary>
        public Color ColorBase => GCPlayerColorData.Variants[colorEnum].BaseColor;
        /// <summary>
        /// GamingCouch player color "dark" variant.
        /// </summary>
        public Color ColorDark => GCPlayerColorData.Variants[colorEnum].Dark;
        /// <summary>
        /// GamingCouch player color "light" variant.
        /// </summary>
        public Color ColorLight => GCPlayerColorData.Variants[colorEnum].Light;
        /// <summary>
        /// GamingCouch player color "off-white" variant.
        /// </summary>
        public Color ColorOffWhite => GCPlayerColorData.Variants[colorEnum].OffWhite;
        private GCPlayerStatus status = GCPlayerStatus.Neutral;
        /// <summary>
        /// GamingCouch player color name in enum format.
        /// </summary>
        private GCPlayerColor colorEnum;
        public GCPlayerColor ColorEnum => colorEnum;
        /// <summary>
        /// GamingCouch player color name in string format.
        /// </summary>
        private string colorName;
        public string ColorName => colorName;
        /// <summary>
        /// Player status.
        /// This can be utilized in different ways to indicate the player's status in the game.
        /// If Players HUD is set to display status text, this will be reflected there as well.
        /// </summary>
        public GCPlayerStatus Status => status;
        private string statusText = "";
        /// <summary>
        /// Players status text.
        /// This can be utilized in different ways to indicate the player's status in the game.
        /// If Players HUD is set to display status text, this will be reflected there as well.
        /// </summary>
        public string StatusText => statusText;
        private GCPlayerEliminationState eliminationState = GCPlayerEliminationState.None;
        public GCPlayerEliminationState EliminationState => eliminationState;
        private GCPlayerFinishState finishState = GCPlayerFinishState.None;
        public GCPlayerFinishState FinishState => finishState;
        /// <summary>
        /// Get the player's broad eliminated status.
        /// </summary>
        public bool IsEliminated => eliminationState != GCPlayerEliminationState.None;
        public bool IsEliminatedPermanent => eliminationState == GCPlayerEliminationState.Permanent;
        public bool IsEliminatedRevokable => eliminationState == GCPlayerEliminationState.Revokable;
        public bool IsFinished => finishState != GCPlayerFinishState.None;
        public bool IsFinishedPermanent => finishState == GCPlayerFinishState.Permanent;
        public bool IsFinishedRevokable => finishState == GCPlayerFinishState.Revokable;
        private float lastSetEliminatedPermanentGameTime = -1;
        public float LastSetEliminatedPermanentGameTime => lastSetEliminatedPermanentGameTime;
        private float lastSetEliminatedRevokableGameTime = -1;
        public float LastSetEliminatedRevokableGameTime => lastSetEliminatedRevokableGameTime;
        private float lastSetRevokeEliminatedGameTime = -1;
        public float LastSetRevokeEliminatedGameTime => lastSetRevokeEliminatedGameTime;
        private float lastSetFinishedPermanentGameTime = -1;
        public float LastSetFinishedPermanentGameTime => lastSetFinishedPermanentGameTime;
        private float lastSetFinishedRevokableGameTime = -1;
        public float LastSetFinishedRevokableGameTime => lastSetFinishedRevokableGameTime;
        private float lastSetRevokeFinishedGameTime = -1;
        public float LastSetRevokeFinishedGameTime => lastSetRevokeFinishedGameTime;
        private float lastSetEliminatedGameTime = -1;
        public float LastSetEliminatedGameTime => lastSetEliminatedGameTime;
        private float lastSetFinishedGameTime = -1;
        public float LastSetFinishedGameTime => lastSetFinishedGameTime;
        private float lastSetRevokeGameTime = -1;
        public float LastSetRevokeGameTime => lastSetRevokeGameTime;
        /// <summary>
        /// Removed. Use LastSetEliminatedGameTime or the explicit permanent/revokable timestamp properties.
        /// </summary>
        [Obsolete("Use LastSetEliminatedGameTime, LastSetEliminatedPermanentGameTime, or LastSetEliminatedRevokableGameTime.", true)]
        public float LastSetEliminatedTime => lastSetEliminatedGameTime;
        /// <summary>
        /// Removed. Use LastSetRevokeEliminatedGameTime.
        /// </summary>
        [Obsolete("Use LastSetRevokeEliminatedGameTime.", true)]
        public float LastSetUneliminatedTime => lastSetRevokeEliminatedGameTime;
        private int score = 0;
        /// <summary>
        /// Get the player's score.
        /// </summary>
        public int Score => score;
        private int lives = 0;
        /// <summary>
        /// Set the player's lives. Depending on the GCPlacementSortCriteria used, this can be used to determine the player's placement.
        /// If hudAutoUpdate is true, the changes will be reflected in the HUD.
        /// </summary>
        public int Lives => lives;
        /// <summary>
        /// Removed. Use LastSetFinishedGameTime or the explicit permanent/revokable timestamp properties.
        /// </summary>
        [Obsolete("Use LastSetFinishedGameTime, LastSetFinishedPermanentGameTime, or LastSetFinishedRevokableGameTime.", true)]
        public float FinishedTime => lastSetFinishedGameTime;
        private int meter = -1;
        /// <summary>
        /// Get the player's meter value (-1-100).
        /// </summary>
        public int Meter => meter;

        /// <summary>
        /// This is called by the GamingCouch script.
        /// You can access all the properties set by this method, such as Index, Color, etc. in your subclasses Start().
        /// </summary>
        /// <param name="options">Options provided by the platform</param>
        internal void _InternalGamingCouchSetup(GCPlayerSetupOptions options)
        {
            index = options.playerIndex;
            playerSeed = options.playerSeed;
            PlayerType = options.type;
            colorEnum = options.colorEnum;
            colorName = options.colorName;
        }

        [Obsolete("SetEliminated has been removed from the game-facing runtime contract. Choose SetEliminatedPermanent(reason) or SetEliminatedRevokable(reason).", true)]
        public void SetEliminated(string reason)
        {
            throw new InvalidOperationException("SetEliminated has been removed. Choose SetEliminatedPermanent or SetEliminatedRevokable.");
        }

        [Obsolete("SetUneliminated has been removed from the game-facing runtime contract. Use SetRevokeEliminated(reason) for revokable elimination.", true)]
        public void SetUneliminated(string reason)
        {
            throw new InvalidOperationException("SetUneliminated has been removed. Use SetRevokeEliminated.");
        }

        public void SetEliminatedPermanent(string reason)
        {
            if (!TryAllowMutation("SetEliminatedPermanent")) return;

            var transition = GCPlayerTransitions.SetEliminatedPermanent(index, eliminationState, reason);

            if (!transition.Accepted)
            {
                EmitEliminationTransitionDiagnostic("SetEliminatedPermanent", transition);
                return;
            }

            ApplyEliminationTransition(
                transition,
                GCPlayerStateTimestampTarget.Permanent,
                "permanently eliminated"
            );
        }

        public void SetEliminatedRevokable(string reason)
        {
            if (!TryAllowMutation("SetEliminatedRevokable")) return;

            var transition = GCPlayerTransitions.SetEliminatedRevokable(index, eliminationState, reason);

            if (!transition.Accepted)
            {
                EmitEliminationTransitionDiagnostic("SetEliminatedRevokable", transition);
                return;
            }

            ApplyEliminationTransition(
                transition,
                GCPlayerStateTimestampTarget.Revokable,
                "revokably eliminated"
            );
        }

        public void SetRevokeEliminated(string reason)
        {
            if (!TryAllowMutation("SetRevokeEliminated")) return;

            var transition = GCPlayerTransitions.SetRevokeEliminated(index, eliminationState, reason);

            if (!transition.Accepted)
            {
                EmitEliminationTransitionDiagnostic("SetRevokeEliminated", transition);
                return;
            }

            ApplyEliminationTransition(
                transition,
                GCPlayerStateTimestampTarget.Revoke,
                "elimination revoked"
            );
        }

        /// <summary>
        /// Set the player's score. Depending on the GCPlacementSortCriteria used, this can be used to determine the player's placement.
        /// If hudAutoUpdate is true, the changes will be reflected in the HUD.
        /// </summary>
        public void SetScore(int newScore, string reason)
        {
            if (!TryAllowMutation("SetScore")) return;

            var transition = GCPlayerTransitions.SetScore(index, score, newScore, reason);

            if (!transition.Accepted) return;

            ApplyScoreTransition(transition);
        }

        /// <summary>
        /// Add to player's score. Depending on the GCPlacementSortCriteria used, this can be used to determine the player's placement.
        /// If hudAutoUpdate is true, the changes will be reflected in the HUD.
        /// </summary>
        public void AddScore(int score, string reason)
        {
            SetScore(this.score + score, reason);
        }

        /// <summary>
        /// Subtract from player's score. Depending on the GCPlacementSortCriteria used, this can be used to determine the player's placement.
        /// If hudAutoUpdate is true, the changes will be reflected in the HUD.
        /// </summary>
        public void SubtractScore(int score, string reason)
        {
            SetScore(this.score - score, reason);
        }

        [Obsolete("SetFinished has been removed from the game-facing runtime contract. Choose SetFinishedPermanent(reason) or SetFinishedRevokable(reason).", true)]
        public void SetFinished(string reason)
        {
            throw new InvalidOperationException("SetFinished has been removed. Choose SetFinishedPermanent or SetFinishedRevokable.");
        }

        public void SetFinishedPermanent(string reason)
        {
            if (!TryAllowMutation("SetFinishedPermanent")) return;

            var transition = GCPlayerTransitions.SetFinishedPermanent(index, finishState, reason);

            if (!transition.Accepted)
            {
                EmitFinishTransitionDiagnostic("SetFinishedPermanent", transition);
                return;
            }

            ApplyFinishTransition(
                transition,
                GCPlayerStateTimestampTarget.Permanent,
                "permanently finished"
            );
        }

        public void SetFinishedRevokable(string reason)
        {
            if (!TryAllowMutation("SetFinishedRevokable")) return;

            var transition = GCPlayerTransitions.SetFinishedRevokable(index, finishState, reason);

            if (!transition.Accepted)
            {
                EmitFinishTransitionDiagnostic("SetFinishedRevokable", transition);
                return;
            }

            ApplyFinishTransition(
                transition,
                GCPlayerStateTimestampTarget.Revokable,
                "revokably finished"
            );
        }

        public void SetRevokeFinished(string reason)
        {
            if (!TryAllowMutation("SetRevokeFinished")) return;

            var transition = GCPlayerTransitions.SetRevokeFinished(index, finishState, reason);

            if (!transition.Accepted)
            {
                EmitFinishTransitionDiagnostic("SetRevokeFinished", transition);
                return;
            }

            ApplyFinishTransition(
                transition,
                GCPlayerStateTimestampTarget.Revoke,
                "finish revoked"
            );
        }

        /// <summary>
        /// Set the player's lives.
        /// </summary>
        public void SetLives(int newLives, string reason)
        {
            if (!TryAllowMutation("SetLives")) return;

            var transition = GCPlayerTransitions.SetLives(index, lives, newLives, reason);

            if (transition.WasClamped)
            {
                EmitStateDiagnostic(
                    GCDiagnosticCodes.ClampedValue,
                    "Lives were clamped.",
                    "SetLives",
                    null,
                    null
                );
            }

            if (!transition.Accepted) return;

            ApplyLivesTransition(transition);
        }

        /// <summary>
        /// Add to player's lives.
        /// </summary>
        /// <param name="lives"></param>
        public void AddLives(int lives, string reason)
        {
            SetLives(this.lives + lives, reason);
        }

        /// <summary>
        /// Subtract from player's lives.
        /// </summary>
        public void SubtractLives(int lives, string reason)
        {
            SetLives(this.lives - lives, reason);
        }

        /// <summary>
        /// Set the player's status and status text.
        /// This status is displayed in the Players HUD if the HUD is configured to display the status.
        /// Player status HUD color will be set based on the status and text can be anything game specific.
        /// Example:
        /// In parking game, while player is finding a spot:
        /// SetStatus(PlayerStatus.Pending, "Finding a spot");
        ///
        /// When spot is found:
        /// SetStatus(PlayerStatus.Success, "Parked!");
        ///
        /// If left without spot:
        /// SetStatus(PlayerStatus.Failure, "Sadge :(");
        /// </summary>
        public void SetStatus(GCPlayerStatus status, string statusText, string reason)
        {
            if (!TryAllowMutation("SetStatus")) return;

            var transition = GCPlayerTransitions.SetStatus(
                index,
                this.status,
                this.statusText,
                status,
                statusText,
                reason
            );

            if (!transition.Accepted) return;

            ApplyStatusTransition(transition);
        }

        /// <summary>
        /// Set the player's meter value ranging from -1 to 100. Depending on the HUD configuration, this will be displayed in the HUD.
        /// Set value to -1 to hide the meter from the HUD (if meter is configured to be displayed in the HUD). 
        /// </summary>
        public void SetMeter(int newMeter, string reason)
        {
            if (!TryAllowMutation("SetMeter")) return;

            var transition = GCPlayerTransitions.SetMeter(index, meter, newMeter, reason);

            if (transition.WasClamped)
            {
                EmitStateDiagnostic(
                    GCDiagnosticCodes.ClampedValue,
                    "Meter was clamped.",
                    "SetMeter",
                    null,
                    null
                );
            }

            if (!transition.Accepted) return;

            ApplyMeterTransition(transition);
        }

        /// <summary>
        /// Get the player's HUD status text to be displayed in the HUD.
        /// This will include the status text and status.
        /// </summary>
        public string GetHudStatusText()
        {
            var str = status.ToString();
            return statusText + "/" + char.ToLower(str[0]) + str[1..]; // set first letter to lowercase
        }

        /// <summary>
        /// Get the player's HUD value to be displayed in the HUD.
        /// </summary>
        virtual public string GetHudValueText()
        {
            throw new Exception("GetHudValueText not implemented. Implement this in your GCPlayer subclass to display a custom value in the HUD.");
        }

        private enum GCPlayerStateTimestampTarget
        {
            Permanent,
            Revokable,
            Revoke,
        }

        private void ApplyEliminationTransition(
            GCPlayerTransitionResult<GCPlayerEliminationState> transition,
            GCPlayerStateTimestampTarget timestampTarget,
            string logAction
        )
        {
            var oldState = transition.PreviousValue;
            var changedAtGameTime = transition.ChangedAtGameTime;
            eliminationState = transition.Value;

            switch (timestampTarget)
            {
                case GCPlayerStateTimestampTarget.Permanent:
                    lastSetEliminatedPermanentGameTime = changedAtGameTime;
                    lastSetEliminatedGameTime = changedAtGameTime;
                    break;
                case GCPlayerStateTimestampTarget.Revokable:
                    lastSetEliminatedRevokableGameTime = changedAtGameTime;
                    lastSetEliminatedGameTime = changedAtGameTime;
                    break;
                case GCPlayerStateTimestampTarget.Revoke:
                    lastSetRevokeEliminatedGameTime = changedAtGameTime;
                    lastSetRevokeGameTime = changedAtGameTime;
                    break;
            }

            GCLog.LogInfo($"Player index {index} {logAction} - reason: " + transition.ReasonText);
            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromElimination(transition));
            OnEliminationStateChanged?.Invoke(new GCPlayerEliminationStateChangedEventArgs(
                index,
                oldState,
                eliminationState,
                transition.ReasonText,
                changedAtGameTime
            ));
        }

        private void ApplyFinishTransition(
            GCPlayerTransitionResult<GCPlayerFinishState> transition,
            GCPlayerStateTimestampTarget timestampTarget,
            string logAction
        )
        {
            var oldState = transition.PreviousValue;
            var changedAtGameTime = transition.ChangedAtGameTime;
            finishState = transition.Value;

            switch (timestampTarget)
            {
                case GCPlayerStateTimestampTarget.Permanent:
                    lastSetFinishedPermanentGameTime = changedAtGameTime;
                    lastSetFinishedGameTime = changedAtGameTime;
                    break;
                case GCPlayerStateTimestampTarget.Revokable:
                    lastSetFinishedRevokableGameTime = changedAtGameTime;
                    lastSetFinishedGameTime = changedAtGameTime;
                    break;
                case GCPlayerStateTimestampTarget.Revoke:
                    lastSetRevokeFinishedGameTime = changedAtGameTime;
                    lastSetRevokeGameTime = changedAtGameTime;
                    break;
            }

            GCLog.LogInfo($"Player index {index} {logAction} - reason: " + transition.ReasonText);
            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromFinish(transition));
            OnFinishStateChanged?.Invoke(new GCPlayerFinishStateChangedEventArgs(
                index,
                oldState,
                finishState,
                transition.ReasonText,
                changedAtGameTime
            ));
        }

        private void ApplyScoreTransition(GCPlayerTransitionResult<int> transition)
        {
            var oldScore = transition.PreviousValue;
            score = transition.Value;

            GCLog.LogInfo($"Player index {index} score set to {score} - reason: " + transition.ReasonText);
            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromInt(transition));
            OnScoreChanged?.Invoke(oldScore, score, transition.ReasonText);
        }

        private void ApplyLivesTransition(GCPlayerTransitionResult<int> transition)
        {
            var oldLives = transition.PreviousValue;
            lives = transition.Value;

            GCLog.LogInfo($"Player index {index} lives set to {lives} - reason: " + transition.ReasonText);
            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromInt(transition));
            OnLivesChanged?.Invoke(oldLives, lives, transition.ReasonText);
        }

        private void ApplyStatusTransition(GCPlayerTransitionResult<GCPlayerStatusValue> transition)
        {
            var oldValue = transition.PreviousValue;
            var value = transition.Value;

            GCLog.LogInfo($"Player index {index} status set to {value.Status} with text {value.StatusText} - reason: " + transition.ReasonText);

            status = value.Status;
            statusText = value.StatusText;

            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromStatus(transition));
            OnStatusTransitionChanged?.Invoke(
                oldValue.Status,
                oldValue.StatusText,
                status,
                statusText,
                transition.ReasonText
            );
            OnStatusChanged?.Invoke(status, statusText, transition.ReasonText);
        }

        private void ApplyMeterTransition(GCPlayerTransitionResult<int> transition)
        {
            var oldMeter = transition.PreviousValue;
            meter = transition.Value;

            AcceptedTransition?.Invoke(GCPlayerAcceptedTransition.FromInt(transition));
            OnMeterChanged?.Invoke(oldMeter, meter, transition.ReasonText);
        }

        private void EmitEliminationTransitionDiagnostic(
            string mutatorName,
            GCPlayerTransitionResult<GCPlayerEliminationState> transition
        )
        {
            EmitStateTransitionDiagnostic(
                mutatorName,
                transition,
                permanentState: GCPlayerEliminationState.Permanent,
                duplicateCode: GCDiagnosticCodes.DuplicateElimination,
                duplicatePermanentMessage: "Player is already permanently eliminated.",
                duplicateRevokableMessage: "Player is already revokably eliminated.",
                invalidTransitionMessage: "Permanent elimination cannot transition back to revokable elimination.",
                invalidRevokeMessage: "Only revokable elimination can be revoked."
            );
        }

        private void EmitFinishTransitionDiagnostic(
            string mutatorName,
            GCPlayerTransitionResult<GCPlayerFinishState> transition
        )
        {
            EmitStateTransitionDiagnostic(
                mutatorName,
                transition,
                permanentState: GCPlayerFinishState.Permanent,
                duplicateCode: GCDiagnosticCodes.DuplicateFinish,
                duplicatePermanentMessage: "Player is already permanently finished.",
                duplicateRevokableMessage: "Player is already revokably finished.",
                invalidTransitionMessage: "Permanent finish cannot transition back to revokable finish.",
                invalidRevokeMessage: "Only revokable finish can be revoked."
            );
        }

        // Elimination and finish stay independent enums per ADR 0003, but they reject for the same
        // three reasons, so the diagnostic path is shared and each family supplies only its wording.
        private void EmitStateTransitionDiagnostic<TState>(
            string mutatorName,
            GCPlayerTransitionResult<TState> transition,
            TState permanentState,
            string duplicateCode,
            string duplicatePermanentMessage,
            string duplicateRevokableMessage,
            string invalidTransitionMessage,
            string invalidRevokeMessage
        ) where TState : struct, Enum
        {
            var oldState = transition.PreviousValue.ToString();
            var requestedState = transition.Value.ToString();

            switch (transition.RejectionReason)
            {
                case GCPlayerTransitionRejectionReason.DuplicateValue:
                    EmitStateDiagnostic(
                        duplicateCode,
                        EqualityComparer<TState>.Default.Equals(transition.Value, permanentState)
                            ? duplicatePermanentMessage
                            : duplicateRevokableMessage,
                        mutatorName,
                        oldState,
                        requestedState
                    );
                    return;
                case GCPlayerTransitionRejectionReason.InvalidTransition:
                    EmitStateDiagnostic(
                        GCDiagnosticCodes.InvalidTransition,
                        invalidTransitionMessage,
                        mutatorName,
                        oldState,
                        requestedState
                    );
                    return;
                case GCPlayerTransitionRejectionReason.InvalidRevoke:
                    EmitStateDiagnostic(
                        GCDiagnosticCodes.InvalidRevoke,
                        invalidRevokeMessage,
                        mutatorName,
                        oldState,
                        requestedState
                    );
                    return;
            }
        }

        private bool TryAllowMutation(string mutatorName)
        {
            if (GamingCouch.Instance == null || GamingCouch.Instance.Status != GCStatus.GameOver)
            {
                return true;
            }

            EmitStateDiagnostic(
                GCDiagnosticCodes.PostGameOverMutation,
                "Player mutation after game over was ignored.",
                mutatorName,
                null,
                null
            );
            return false;
        }

        private void EmitStateDiagnostic(
            string code,
            string message,
            string mutatorName,
            string oldState,
            string requestedState
        )
        {
            var context = new GCDiagnosticContext()
                .AddDetail("mutator", mutatorName);

            if (index >= 0)
            {
                context.WithPlayerIndex(index);
            }

            if (oldState != null)
            {
                context.AddDetail("oldState", oldState);
            }

            if (requestedState != null)
            {
                context.AddDetail("requestedState", requestedState);
            }

            GCDiagnostics.Emit(
                code,
                GCDiagnosticSeverity.Warning,
                GCDiagnosticSourceAreas.State,
                message,
                context
            );
        }
    }
}
